force-app/main/default/objects/Account_High_Risk__e/Account_High_Risk__e.object-meta.xml
<CustomObject>
    <label>Account High Risk</label>
    <pluralLabel>Accounts High Risk</pluralLabel>
</CustomObject>

force-app/main/default/objects/Account_High_Risk__e/fields/Account_Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Id__c</fullName>
    <label>Account Owner Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_High_Risk__e/fields/Risk__c.field-meta.xml
<CustomField>
    <fullName>Risk__c</fullName>
    <label>Risk</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountPlataformEventPublisher.cls
public with sharing class AccountPlataformEventPublisher {
   
    public static void publishAccountEvent(List<Account> TrgAccsNew, List<Account> TrgAccsOld, Map<id,Account> mapAccsNew,Map<id,Account> mapAccsOld ){
        
        List<Account> updatedAccts = new  List<Account>();
        for(Account ac:TrgAccsNew){
            if(ac.Risk__c != mapAccsOld.get(ac.id).Risk__c ){
                updatedAccts.add(ac); 
            }    
        }
        
        List<Account_High_Risk__e> accountEvents = new List<Account_High_Risk__e>();
        for(Account acc : updatedAccts) {
            Account_High_Risk__e eve = new Account_High_Risk__e();    
            eve.Account_Owner_Id__c = acc.OwnerId;
            eve.Risk__c = acc.Risk__c;
            eve.AccountId__c = acc.id;
            accountEvents.add(eve);
        }

        if(accountEvents.size()>0){
            EventBus.publish(accountEvents);
        }
    }
}